// Mocks generated by Mockito 5.4.4 from annotations
// in network_app/test/features/towers/domain/usecases/get_nearby_towers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:network_app/core/error/failures.dart' as _i5;
import 'package:network_app/features/towers/domain/entities/cellular_tower.dart'
    as _i6;
import 'package:network_app/features/towers/domain/repositories/tower_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TowerRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTowerRepository extends _i1.Mock implements _i3.TowerRepository {
  MockTowerRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.CellularTower>>> getNearbyTowers({
    required double? latitude,
    required double? longitude,
    double? radiusKm = 10.0,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNearbyTowers,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #radiusKm: radiusKm,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.CellularTower>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.CellularTower>>(
          this,
          Invocation.method(
            #getNearbyTowers,
            [],
            {
              #latitude: latitude,
              #longitude: longitude,
              #radiusKm: radiusKm,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.CellularTower>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CellularTower>> getTowerById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTowerById,
          [id],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.CellularTower>>.value(
                _FakeEither_0<_i5.Failure, _i6.CellularTower>(
          this,
          Invocation.method(
            #getTowerById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.CellularTower>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> pingTower(String? towerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #pingTower,
          [towerId],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
            _FakeEither_0<_i5.Failure, int>(
          this,
          Invocation.method(
            #pingTower,
            [towerId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CellularTower>> updateTowerStats(
          String? towerId) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTowerStats,
          [towerId],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i6.CellularTower>>.value(
                _FakeEither_0<_i5.Failure, _i6.CellularTower>(
          this,
          Invocation.method(
            #updateTowerStats,
            [towerId],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.CellularTower>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.CellularTower>>>
      getCachedTowers() => (super.noSuchMethod(
            Invocation.method(
              #getCachedTowers,
              [],
            ),
            returnValue: _i4
                .Future<_i2.Either<_i5.Failure, List<_i6.CellularTower>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.CellularTower>>(
              this,
              Invocation.method(
                #getCachedTowers,
                [],
              ),
            )),
          ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.CellularTower>>>);
}
